"""
This script reads one of the .dat files generated by the fractal generator,
iterates over each point in the complex grid and assigns each complex point a
color based on a color_function and a color_palette.
"""

from PIL import Image

# We first start by reading in the .dat file
INPUT_FILE = '../fractal_generator/sample_fractal_512_512.dat'

with open(INPUT_FILE) as data_in:
    # We read the first four lines first, telling us what properties the fractals has 
    RESOLUTION_X = int(next(data_in).split(' ')[-1])
    RESOLUTION_Y = int(next(data_in).split(' ')[-1])
    NUMBER_OF_ITERATIONS = int(next(data_in).split(' ')[-1])
    COMPLEX_SEED = complex((next(data_in).split(' ')[-1]))

    # We now initialize an empty bitmap 
    image = Image.new('RGB', (RESOLUTION_X, RESOLUTION_Y ), 'black')
    pixels = image.load()
    
    # Iterate over the complex numbers, given by their indices in the complex grid
    try:
        while data_in.next():
            in_line = next(data_in).split(',')
            x = int(in_line[0])
            y = int(in_line[1])
            iterations = int(in_line[2])
            if iterations == NUMBER_OF_ITERATIONS:
                pixels[x, y] = (255,255,255)
    except:
        # Done!
        pass
    image.show()
